/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.42                          *
*        Compiled Aug  1 2017, 12:37:20                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "ff.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x02)
#define ID_BUTTON_0     (GUI_ID_USER + 0x03)


// USER START (Optionally insert additional defines)
#define ONCE_READ_NYTE 512                              //每次读写的字节
#define IMAGE_Chache_ADR  (0xa0000000+0x3FC00)          //图片的缓冲地址一直到动态内存的起始地址    
#define IMAGE_Chache_Size (0xC0400)  
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
static UINT image_num = 0;
static FIL FILE_Image;

unsigned char *acBuffer = (unsigned char *)IMAGE_Chache_ADR; //一个比较大的空间
UINT bw;
FRESULT fl_error;
unsigned long read_length;
unsigned char read_flag;
GUI_MEMDEV_Handle hMem;
WM_MESSAGE * disp_pMsg;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 322, 209, 80, 29, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
void switch_jpeg(WM_HWIN hItem);
void disp_image(void);
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
			   switch_jpeg(pMsg->hWin);//切换图片
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
		case WM_PAINT: {
		 disp_image();//显示图片
	 }	
		break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
/*
		切换图片的功能
*/
void switch_jpeg(WM_HWIN hItem)
{
	if( ++image_num > 6)
	{
		image_num = 0;
	}
	WM_InvalidateWindow(hItem); //无效化窗口
	read_flag = 1;
}
/* 
		背景重绘
*/
void disp_image(void)
{
	char *fil_name;
	switch(image_num)
	{
		case 0:fil_name="/1.dta"; break;
		case 1:fil_name="/2.dta"; break;
		case 2:fil_name="/3.dta"; break;
		case 3:fil_name="/4.dta"; break;
		case 4:fil_name="/5.dta"; break;
		case 5:fil_name="/6.dta"; break;
		case 6:fil_name="/7.dta"; break;
		default: fil_name="/1.dta"; break;
	}
  if(FR_OK == f_open(&FILE_Image,_T(fil_name), FA_OPEN_EXISTING | FA_READ | FA_OPEN_ALWAYS) && read_flag)
	{  
		read_flag = 0;
		for(read_length = 0, bw = 0; read_length < FILE_Image.obj.objsize ; read_length = read_length + bw)
		{
			if( FILE_Image.obj.objsize >= read_length + ONCE_READ_NYTE)
			{
				fl_error = f_read(&FILE_Image, acBuffer + read_length, ONCE_READ_NYTE , &bw);
			}
			else
			{
				fl_error = f_read(&FILE_Image, acBuffer + read_length, FILE_Image.obj.objsize - read_length , &bw);
			}
			
			if(fl_error || IMAGE_Chache_Size < FILE_Image.obj.objsize)
			{
				break; 
			}
		}
	}
	if(FR_OK == fl_error)
	{
		//显示图片
		GUI_DrawStreamedBitmapAuto(acBuffer, 0, 0);
	}
	f_close(&FILE_Image);
}
// USER END

/*************************** End of file ****************************/
